### ISSUE TITLE
Charmonium asks for a version of Charm that doesn't exist yet

### ISSUE THREAD

**Issue by DeadPigman17** [svenhjol/CharmoniumForge#1]
I downloaded the latest version of both Charm and Charmonium for Forge. When launching the game, it says that Charmonium needs Charm 2.2.0 or higher, but the current latest version of Charm for Forge is 2.1.9.

**Comment by stevojhall** [comment]
you need to google charm reforged, then click curse forge link (curse dosen't seem to find charm reforged yet)

**Comment by DeadPigman17** [comment]
Ok, thanks!
