### ISSUE TITLE
Dependency Question

### ISSUE THREAD

**Issue by TheIrishStud** [svenhjol/CharmoniumForge#11]
Does Charmonium for Forge work without Charm like the Fabric version details or is it required in order for the Forge version to work correctly? Most of the Charm features already exist within mods already installed and working in my mod list and the remaining features involve modifying world generation which breaks my saves after traveling beyond a 1000 x 1000 block radius in every direction until Minecraft crashes.

**Comment by svenhjol** [comment]
At the moment, only the 1.17 fabric version of Charmonium works on the client side without Charm.  When Forge updates to 1.17, we will look at porting it.

**Comment by TheIrishStud** [comment]
Any chance for a possible 1.16.5 Forge port considering Caves & Cliffs won't be completed and allow the release of a stable Forge version until after 1.18?

**Comment by svenhjol** [comment]
No sorry I won't be porting to earlier versions, I don't have the time

**Comment by TheIrishStud** [comment]
Thanks for the information.
