### ISSUE TITLE
[Question] Dynamic Surroundings compatibilty

### ISSUE THREAD

**Issue by Teacyn** [svenhjol/CharmoniumForge#2]
This isn't really an issue, but I was wondering how compatible this mod is with https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings

Since that mod also adds a bunch of ambient sounds. I'd be using this mod primarily for the new music.

**Comment by StygianEmperor** [comment]
I actually used them simultaneously for a while, and they did both work (without notable redundancy I might add), then had to temporarily drop Charmonium when Charm got updated for Forge without Charmonium getting a compatible update, I think? But with the update I will try to reincorporate Charmonium back into my game.

I believe a third mod, such as Extreme Sound Muffler ([Forge](https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler)/[Fabric](https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler-fabric)) could turn off any redundant or overlapping sounds.
