### ISSUE TITLE
The latest Forge version of this mod requires Charm 2.2.0, which is Fabric.

### ISSUE THREAD

**Issue by MagmaBro123** [svenhjol/CharmoniumForge#3]
Your requiring a version of Charm that uses a completely different modloader.
![image](https://user-images.githubusercontent.com/51277766/103817884-60e72700-501c-11eb-8c8d-0451b9f6ea1d.png)
![image](https://user-images.githubusercontent.com/51277766/103817855-562c9200-501c-11eb-8651-ec46069493e8.png)

**Comment by F43nd1r** [comment]
Fabric and forge have been split. https://www.curseforge.com/minecraft/mc-mods/charm-reforged
