### ISSUE TITLE
Charmonium causes Charm to ignore some parts of it's config

### ISSUE THREAD

**Issue by NJL5390** [svenhjol/CharmoniumForge#7]
Minecraft Version: 1.16.5
Forge Version: 36.0.21
Charm Version: 2.2.2
Charmonium Version: 2.2.2

Latest Log: https://pastebin.com/Thm9Nza3

When testing a modpack I was putting together lately I noticed that when I added Charmonium to the pack certain aspects of Charm got reactivated that I had disabled previously, such as Husks dropping sand or Strays dropping blue ice. When I looked at Charm's config file I found it was still as it was when I last saved it, so nothing had happened to the file itself.

What seems to be happening is that Charmonium appears to cause Charm to ignore it's config file or revert back to the default configuration without changing the file itself. This only started happening when I added Charmonium and when Charmonium is not present, Charm uses it's config file properly and does not ignore it.

If you need any more information on top of this then I'd be happy to help.

**Comment by The-Bernician-Lamb** [comment]
Nevermind, I guess. After testing this mod again after a long time I find that I can no longer reproduce this issue, so I guess it's all fine? 

I'll reopen this issue if this bug crops up again.
