### ISSUE TITLE
Game Crashes on Startup after disabling certain types of ambience in Charmoniums's config

### ISSUE THREAD

**Issue by NJL5390** [svenhjol/CharmoniumForge#8]
Minecraft Version: 1.16.5
Forge Version: 36.0.21
Charm Version: 2.2.2
Charmonium Version: 2.2.2

Latest Log: https://pastebin.com/zUSPkS7i

Crash Report: https://pastebin.com/kufx7QVf

When configuring this mod, I've noticed that the game crashes on startup after I disabled certain types of ambience such as swamp ambience, plains ambience and forest ambience. 

This occurs even when no other mods aside from Charm are installed. If I leave the config file as the default then the game loads just fine and doesn't crash, it only starts crashing when I alter the config file.

If you need any more information about this I'd be happy to help!

**Comment by The-Bernician-Lamb** [comment]
After trying to reproduce this issue in more recent versions I cannot seem to reproduce this issue anymore, so I'll just close this now.

I'll reopen this issue if it pops up again.
